name: 'Deploy'

on:
  workflow_dispatch: 

jobs:
  deploy:
    name: "Deploy to dev"
    uses: mkoyanhakob/testing-workflows/.github/workflows/reusable-deploy.yaml@main
    with:
      environment: dev
    secrets: inherit