name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        options:
          - 'dev'
          - 'test'
        type: choice
        description: "Environment to deploy."
        default: 'dev'

jobs:
  deploy:
    name: "Deploy to ${{ inputs.environment }}"
    uses: mkoyanhakob/testing-workflows/.github/workflows/reusable-deploy.yaml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit